server:
  port: 8761

spring:
  application:
    name: filink-eureka

eureka:
  client:
    fetch-registry: false #不从eureka上获取服务的注册信息
    register-with-eureka: false #不把自己注册到eureka上
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: eureka-server #eureka实例的主机名