server:
  port: 8070

spring:
  application:
    name: configclient

#设置服务注册中心地址
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址