server:
  port: 8888
spring:
  application:
    name: githubconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flea00/firstspringcloud.git
          search-paths: config
          username: flea00
          password: fleaflea00
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/