server:
  port: 8400

spring:
  application:
    name: feign

#设置服务注册中心地址
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址

#  配置feign使用熔断
feign:
  hystrix:
    enabled: true